### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /((?:\w \s*::\s*)*)FindPrependicularDistance(/:...

### ISSUE THREAD

**Issue by FundamentalEq** [AnickaBurova/cpp-refactor#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [cpp-refactor](https://github.com/AnickaBurova/cpp-refactor) package, v2.2.0

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /((?:\w \s*::\s*)*)FindPrependicularDistance(/: Unterminated group

```
At /home/aakash/.atom/packages/cpp-refactor/lib/cpp-refactor.coffee:382

SyntaxError: Invalid regular expression: /((?:\w \s*::\s*)*)FindPrependicularDistance(/: Unterminated group
    at RegExp (native)
    at Object.find_class (/home/aakash/.atom/packages/cpp-refactor/lib/cpp-refactor.coffee:382:25)
    at atom-workspace.subscriptions.add.atom.commands.add.cpp-refactor:find-class (/home/aakash/.atom/packages/cpp-refactor/lib/cpp-refactor.coffee:50:91)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/opt/atom/resources/app.asar/src/atom-environment.js:1181:28)
    at EventEmitter.outerCallback (/opt/atom/resources/app.asar/src/application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  4x -1:16.8.0 core:move-right (input.hidden-input)
  2x -1:13.6.0 core:move-down (input.hidden-input)
     -1:13.1.0 autocomplete-plus:confirm (input.hidden-input)
     -1:11.3.0 intentions:highlight (input.hidden-input)
  2x -1:11 core:undo (input.hidden-input)
     -1:05.9.0 intentions:highlight (input.hidden-input)
     -1:05.7.0 core:save (input.hidden-input)
  2x -1:05.1.0 core:move-down (input.hidden-input)
  3x -1:04.4.0 core:move-up (input.hidden-input)
undefined -1:00.0 core:move-down (input.hidden-input)
 85x -0:55 core:move-up (input.hidden-input)
 29x -0:45.6.0 core:move-down (input.hidden-input)
 16x -0:39.1.0 core:move-up (input.hidden-input)
 25x -0:35.8.0 core:move-right (input.hidden-input)
     -0:00.1.0 cpp-refactor:find-class (span.syntax--entity.syntax--name.syntax--function.syntax--python)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-spell"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (active)
atom-cscope, v0.15.0 (inactive)
atom-debugger, v0.1.6 (inactive)
autocomplete-clang, v0.10.0 (active)
autocomplete-python, v1.8.26 (active)
busy-signal, v1.2.0 (active)
cpp-refactor, v2.2.0 (inactive)
debugger, v0.0.1 (active)
file-icons, v2.0.8 (active)
gpp-compiler, v3.0.7 (active)
highlight-line, v0.11.2 (active)
highlight-selected, v0.11.2 (active)
intentions, v1.1.2 (active)
linter, v1.11.18 (active)
linter-spell, v0.12.6 (inactive)
linter-spell-html, v0.6.1 (inactive)
python-debugger, v0.1.0 (active)
python-indent, v1.0.0 (active)
switch-header-source, v0.22.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by AnickaBurova** [comment]
Fixed
