### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /((?:\w \s*::\s*)*));/: Unmatched ')'

### ISSUE THREAD

**Issue by lukaskiss222** [AnickaBurova/cpp-refactor#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [cpp-refactor](https://github.com/AnickaBurova/cpp-refactor) package 2.2.0

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /((?:\w \s*::\s*)*));/: Unmatched ')'

```
At /home/lukas/.atom/packages/cpp-refactor/lib/cpp-refactor.coffee:382

SyntaxError: Invalid regular expression: /((?:\w \s*::\s*)*));/: Unmatched ')'
    at RegExp (native)
    at Object.find_class (/packages/cpp-refactor/lib/cpp-refactor.coffee:382:25)
    at /packages/cpp-refactor/lib/cpp-refactor.coffee:50:91)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
 11x -2:20.4.0 core:backspace (input.hidden-input)
     -2:13.9.0 editor:newline (input.hidden-input)
     -2:05.4.0 core:backspace (input.hidden-input)
     -1:58.8.0 snippets:next-tab-stop (input.hidden-input)
     -1:58.8.0 snippets:expand (input.hidden-input)
     -1:58.8.0 editor:indent (input.hidden-input)
     -1:58.2.0 core:backspace (input.hidden-input)
 10x -1:56 find-and-replace:find-next (input.hidden-input)
     -1:52.4.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:48.3.0 encoding-selector:show (atom-text-editor.editor)
  2x -1:39.7.0 atom-beautify:beautify-editor (input.hidden-input)
     -0:25.4.0 core:save (input.hidden-input)
  2x -0:19.4.0 core:backspace (input.hidden-input)
     -0:18.4.0 core:save (input.hidden-input)
     -0:12.6.0 autocomplete-clang:toggle (input.hidden-input)
     -0:07.6.0 cpp-refactor:find-class (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-python-run 0.7.3 
autocomplete-awk 0.1.2 
autocomplete-clang 0.10.0 
autocomplete-haskell 0.7.2 
autocomplete-html-entities 0.1.0 
autocomplete-java 1.2.5 
autocomplete-js-import 1.4.0 
autocomplete-json 5.4.0 
autocomplete-modules 1.6.8 
autocomplete-python 1.8.62 
autocomplete-xml 0.9.4 
cpp-refactor 2.2.0 
git-commit 1.5.3 
git-diff-details 1.4.0 
git-log 0.4.1 
git-plus 7.3.3 
git-status 0.3.4 
git-time-machine 1.5.6 
haskell-ghc-mod 1.19.7 
haskell-grammar 0.4.0 
Hydrogen 1.7.0 
ide-haskell 1.9.6 
javascript-snippets 1.2.1 
language-haskell 1.12.1 
python-autopep8 0.1.3 
python-debugger 0.2.0 
python-indent 1.0.2 
python-tools 0.6.9 
qolor 0.4.1 
rails-i18n-autocomplete 0.4.0 
tree-view-git-status 1.3.1 
```

**Comment by AnickaBurova** [comment]
Fixed
